# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Changes
on:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      mongo:
          image: mongo
          env:
            MONGO_INITDB_ROOT_USERNAME: deepscribe
            MONGO_INITDB_ROOT_PASSWORD: password
          ports:
            - 27017:27017
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Add npm registry authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Initialize prod terraform for validation
        working-directory: ./terraform/prod
        run: terraform init -input=false -backend=false
      - name: Validate prod terraform
        working-directory: ./terraform/prod
        run: terraform validate
      - name: Initialize staging terraform for validation
        working-directory: ./terraform/staging
        run: terraform init -input=false -backend=false
      - name: Validate staging terraform
        working-directory: ./terraform/staging
        run: terraform validate
